@startuml


skinparam rectangle {
    roundCorner<<Process>> 54
}

note "All processes log events to journald" as logNote

frame WildlifeCam {
  

  frame RaspberryPi {
    rectangle "Take Photo" <<Process>> as rpiPhoto
    rectangle "5 Minute Timer" <<Process>> as rpiTime
    rectangle "Detect Motion" <<Process>> as rpiMotion
    rectangle "External Subscriber" <<Process>> as rpiExternal
    rectangle "Rain Detector" <<Process>> as rpiRain
    rectangle "Wipe Controller" <<Process>> as rpiWipe
    rectangle "Access Point" as rpiAcc
    rectangle "Web Server" <<Process>> as rpiWeb
    
  }
  
  frame ESP8266 {
    rectangle "Monitor Button" <<Process>> as espTrig
    rectangle "Publish Event" <<Process>> as espPublish
  }
  
  frame RPico {
    rectangle "Rain detection" <<Process>> as pcDetect
    rectangle "Servo Controller" <<Process>> as pcWipe
  }
}

frame Drone {
  rectangle "Connect" <<Process>> as dConnect
  rectangle "Download Images" <<Process>> as dSync
  rectangle "Log Wifi" <<Process>> as dLogWifi
}

frame Cloud {
  rectangle "Annotate" <<Process>> as cAnn
  rectangle "Upload" <<Process>> as cUp
}

logNote .-right- RaspberryPi


pcDetect -up-> rpiRain : Serial
rpiRain -> rpiWipe : MQTT
rpiWipe -> pcWipe : Serial

rpiTime -> rpiPhoto
rpiMotion -> rpiPhoto
rpiExternal -left-> rpiPhoto

espTrig -> espPublish
espPublish -up-> rpiExternal : MQTT

dConnect -down-> rpiAcc
dSync <-> rpiWeb : HTTP

Drone -> Cloud : "Transfer Images"




@enduml
