@startuml

skinparam rectangle {
    roundCorner<<Process>> 54
}

frame WildlifeCam {

  frame RaspberryPi {
    rectangle "Take Photo" <<Process>> as rpiPhoto
    rectangle "5 Minute Timer" <<Process>> as rpiTime
    rectangle "Detect Motion" <<Process>> as rpiMotion
    rectangle "External Subscriber" <<Process>> as rpiExternal
    rectangle "Rain Detector" <<Process>> as rpiRain
    rectangle "Wipe Controller" <<Process>> as rpiWipe
    rectangle "Access Point" as rpiAcc
    rectangle "Web Server" <<Process>> as rpiWeb
  }
  note top of RaspberryPi: All processes log events to journald
  
  frame ESP8266 {
    rectangle "Monitor Button" <<Process>> as espTrig
    rectangle "Publish Event" <<Process>> as espPublish
  }
  
  frame RPico {
    rectangle "Rain detection" <<Process>> as pcDetect
    rectangle "Servo Controller" <<Process>> as pcWipe
  }

}

frame Drone {
  label " " as droneLabel
  rectangle "Connect" <<Process>> as dConnect
  rectangle "Download Images" <<Process>> as dSync
  rectangle "Log Wifi" <<Process>> as dLogWifi
}

frame Cloud {
  label " " as cloudLabel
  rectangle "Annotate" <<Process>> as cAnn
  rectangle "Upload" <<Process>> as cUp
}


pcDetect -d-> rpiRain : Serial
rpiRain -> rpiWipe : MQTT
rpiWipe -u-> pcWipe : Serial

rpiTime -u-> rpiPhoto
rpiMotion -u-> rpiPhoto
rpiExternal -u-> rpiPhoto

espTrig -> espPublish
espPublish -u-> rpiExternal : MQTT

dConnect -> rpiAcc
dSync <-> rpiWeb : HTTP

droneLabel -d-> cloudLabel : "Transfer Images"

'placement stuff'

rpiMotion -[hidden]right-> rpiExternal
rpiTime -[hidden]right-> rpiExternal

rpiWeb -[hidden]r-> rpiTime
rpiAcc -[hidden]d-> rpiWeb
dSync -[hidden]u-> dConnect

rpiAcc -[hidden]l-> rpiRain
rpiAcc -[hidden]l-> rpiWipe
rpiAcc -[hidden]l-> rpiPhoto

cloudLabel -[hidden]l-> cAnn
droneLabel -[hidden]u-> dLogWifi
droneLabel -[hidden]l-> dSync


@enduml
