@startuml Rain Detection and Lens Wiping


title "Rain Detection and Lens Wiping"

participant Pico
participant "Raspberry Pi" as RPi
queue MQTT

Pico -> RPi : Sense Rain
RPi -> MQTT : Publish Rain Event 
MQTT -> RPi : Receive Rain Event
loop wiping lens
  RPi -> Pico : Send wiper angle
end

@enduml