@startuml

box "ESP32" #LightGreen
  participant "Monitor Button" as espBtn
  participant "MQTT Publisher" as espPub
end box

box "MQTT Broker" #LightBlue
  participant "MQTT" as mqtt
end box

box "Raspberry Pi" #LightCoral
  participant "MQTT Subscriber" as rpiSub
  participant "Take Photo" as rpiPhoto
  participant "Create Metadata" as rpiMeta
end box

espBtn -> espPub : Button Pressed
espPub -> mqtt : Publish\n"External" Event
mqtt -> rpiSub : Consume\n"External" Event
rpiSub -> rpiPhoto : Take Photo\n(Trigger: External)
rpiPhoto <- rpiPhoto : Get Current Time
rpiPhoto -> rpiMeta : Trigger: External
rpiMeta -> rpiPhoto : Return Metadata
rpiPhoto <- rpiPhoto : Take Photo\nUsing rpicam
rpiPhoto -> rpiPhoto : Save Photo\n& Metadata
@enduml
