@startuml Motion Photo

  participant "Save Motion" as rpiSMotion
  participant "Detect Motion" as rpiDMotion
  participant "Create Metadata" as rpiMeta

rpiSMotion -> rpiSMotion : Get Current Time
rpiSMotion -> rpiSMotion : Take Photo Using rpicam

loop
    rpiSMotion -> rpiSMotion : Get Current Time
    alt Time Since Last Photo >= 1 Second
      rpiSMotion -> rpiSMotion : Take Photo Using rpicam
      rpiSMotion -> rpiDMotion : Previous and Current Photo
      rpiDMotion -> rpiSMotion : return Motion/No Motion
      alt Motion Detected
        rpiSMotion -> rpiMeta : Trigger: Motion
        rpiMeta -> rpiSMotion : Return Metadata
        rpiSMotion -> rpiSMotion : Save Photo & Metadata
      end
      rpiSMotion -> rpiSMotion : Remove Previous Photo
      rpiSMotion -> rpiSMotion : Previous Time and Photo =\nCurrent Time and Photo
    end
end
@enduml
