@startuml Timed Photo

  participant "Timer" as rpiTime
  participant "Take Photo" as rpiPhoto
  participant "Create Metadata" as rpiMeta

loop
  alt Seconds since\nlast triggered >= 300
    rpiTime -> rpiPhoto : Trigger: Time
    rpiPhoto <- rpiPhoto : Get Current Time
    rpiPhoto -> rpiMeta : Trigger: Time
    rpiMeta -> rpiPhoto : Return Metadata
    rpiPhoto <- rpiPhoto : Take Photo\nUsing rpicam
    rpiPhoto -> rpiPhoto : Save Photo\n& Metadata
  else Else
    rpiTime -> rpiTime : Wait 1 second
  end
end
@enduml
